sudo: required
language: rust
rust:
  - stable
services:
  - docker
# env:
#   - DOCKER_COMPOSE_VERSION=1.14.0

# Need to cache the whole `.cargo` directory to keep .crates.toml for cargo-update to work.
cache:
  directories:
    - /home/travis/.cargo

# Don't cache the cargo registry.
before_cache:
  - rm -rf /home/travis/.cargo/registry

before_install:
  - docker-compose up -d
  - rustup install nightly-2018-11-09

script:
  # Test doc samples.
  - cd wither && cargo +nightly-2018-11-09 test --features docinclude --doc; cd -
  - cd wither_derive && cargo +nightly-2018-11-09 test --doc; cd -
  # Test code generation & compilation.
  - cargo +nightly-2018-11-09 test -p wither_tests -p wither_derive --tests --lib
  # Test against MongoDB 3.2.
  - HOST=localhost PORT=27017 cargo test -p wither --tests --lib -- --test-threads=1
  # Test against MongoDB 3.4.
  - HOST=localhost PORT=27117 cargo test -p wither --tests --lib -- --test-threads=1
  # Test against MongoDB 3.6.
  - HOST=localhost PORT=27217 cargo test -p wither --tests --lib -- --test-threads=1
  # Test against MongoDB 4.0.
  - HOST=localhost PORT=27317 cargo test -p wither --tests --lib -- --test-threads=1
