version: '3'
services:
  mongodb-4.4:
    image: mongo:4.4
    ports:
      - 27017:27017

  # Enable the services below as needed for local testing.

  # mongodb-4.2:
  #   image: mongo:4.2
  #   ports:
  #     - 27117:27017

  # mongodb-4.0:
  #   image: mongo:4.0
  #   ports:
  #     - 27217:27017

  # mongodb-3.6:
  #   image: mongo:3.6
  #   ports:
  #     - 27317:27017

  # mongo:
  #   image: mongo
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #   ports:
  #     - 27017:27017

  # mongo-express:
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
